export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_LOADING = "GET_POST_LOADING";
export const GET_POST_ERROR = "GET_POST_ERROR";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_LOADING = "DELETE_POST_LOADING";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
